# Generated by Django 5.1.3 on 2025-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20),
        ),
    ]
